[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/', '@rari-capital/solmate/src/=lib/solmate/src/']

# See more config options https://github.com/gakonst/foundry/tree/master/config